const images = {
  I: require("./img/I.png"),
  want: require("./img/want.png"),
  help: require("./img/help.png"),
  more: require("./img/more.png"),
  you: require("./img/you.png"),
  turn: require("./img/turn.png"),
  see: require("./img/see.png"),
  "all done": require("./img/alldone.png"),
  hello: require("./img/hello.png"),
  goodbye: require("./img/goodbye.png"),
  yes: require("./img/yes.png"),
  no: require("./img/no.png"),
  please: require("./img/please.png"),
  "thank you": require("./img/thankyou.png"),
  again: require("./img/again.png"),
  now: require("./img/now.png"),
  later: require("./img/later.png"),
  first: require("./img/first.png"),
  next: require("./img/next.png"),
  last: require("./img/last.png"),
  tired: require("./img/tired.png"),
  happy: require("./img/happy.png"),
  sad: require("./img/sad.png"),
  angry: require("./img/angry.png"),
  excited: require("./img/excited.png"),
  hurt: require("./img/hurt.png"),
  classroom: require("./img/classroom.png"),
  school: require("./img/school.png"),
  home: require("./img/home.png"),
  playground: require("./img/playground.png"),
  cafeteria: require("./img/cafeteria.png"),
  bathroom: require("./img/bathroom.png"),
  lego: require("./img/lego.png"),
  bubbles: require("./img/bubbles.png"),
  puzzle: require("./img/puzzle.png"),
  "toy cars": require("./img/toycars.png"),
  blocks: require("./img/blocks.png"),
  kitchen: require("./img/kitchen.png"),
  game: require("./img/game.png"),
  ball: require("./img/ball.png"),
  "play doh": require("./img/playdoh.png"),
  "baby doll": require("./img/doll.png"),
  "doll house": require("./img/dollhouse.png"),
  yogurt: require("./img/yogurt.png"),
  pretzel: require("./img/pretzel.png"),
  popcorn: require("./img/popcorn.png"),
  crackers: require("./img/crackers.png"),
  "fruit snack": require("./img/fruitsnack.png"),
  "fish crackers": require("./img/fishcrackers.png"),
  sandwich: require("./img/sandwich.png"),
  pasta: require("./img/pasta.png"),
  pizza: require("./img/pizza.png"),
  "chicken nuggets": require("./img/chickennuggets.png"),
  cheese: require("./img/cheese.png"),
  hamburger: require("./img/hamburger.png"),
  water: require("./img/water.png"),
  milk: require("./img/milk.png"),
  "chocolate milk": require("./img/chocolatemilk.png"),
  "apple juice": require("./img/applejuice.png"),
  "juice box": require("./img/juicebox.png"),
  straw: require("./img/straw.png"),
  eyes: require("./img/eyes.png"),
  ear: require("./img/ear.png"),
  mouth: require("./img/mouth.png"),
  nose: require("./img/nose.png"),
  teeth: require("./img/teeth.png"),
  hair: require("./img/hair.png"),
  arm: require("./img/arm.png"),
  leg: require("./img/leg.png"),
  hand: require("./img/hand.png"),
  foot: require("./img/foot.png"),
  stomach: require("./img/stomach.png"),
  back: require("./img/back.png"),
  red: require("./img/red.png"),
  blue: require("./img/blue.png"),
  green: require("./img/green.png"),
  yellow: require("./img/yellow.png"),
  purple: require("./img/purple.png"),
  orange: require("./img/orange.png"),
  crayons: require("./img/crayons.png"),
  markers: require("./img/markers.png"),
  glue: require("./img/glue.png"),
  scissors: require("./img/scissors.png"),
  paint: require("./img/paint.png"),
  draw: require("./img/draw.png"),
  circle: require("./img/circle.png"),
  triangle: require("./img/triangle.png"),
  rectangle: require("./img/rectangle.png"),
  square: require("./img/square.png"),
  diamond: require("./img/diamond.png"),
  oval: require("./img/oval.png"),
  "t-shirt": require("./img/tshirt.png"),
  pants: require("./img/pants.png"),
  jacket: require("./img/jacket.png"),
  shorts: require("./img/shorts.png"),
  sneakers: require("./img/sneakers.png"),
  socks: require("./img/socks.png"),
  sunny: require("./img/sunny.png"),
  rain: require("./img/rain.png"),
  cloudy: require("./img/cloudy.png"),
  snow: require("./img/snow.png"),
  windy: require("./img/windy.png"),
  "partly cloudy": require("./img/partlycloudy.png"),
  dog: require("./img/dog.png"),
  cat: require("./img/cat.png"),
  bird: require("./img/bird.png"),
  bunny: require("./img/bunny.png"),
  frog: require("./img/frog.png"),
  fish: require("./img/fish.png"),
  car: require("./img/car.png"),
  train: require("./img/train.png"),
  boat: require("./img/boat.png"),
  bicycle: require("./img/bicycle.png"),
  bus: require("./img/bus.png"),
  airplane: require("./img/airplane.png"),
  playbutton: require("./playbutton.png"),
  "home-tab": require("./img/categories/home.png"),
  "greetings-tab": require("./img/categories/greetings.png"),
  "feelings-tab": require("./img/categories/feelings.png"),
  "time-tab": require("./img/categories/time.png"),
  "places-tab": require("./img/categories/places.png"),
  "toys-tab": require("./img/categories/toys.png"),
  "snacks-tab": require("./img/categories/snacks.png"),
  "food-tab": require("./img/categories/food.png"),
  "drinks-tab": require("./img/categories/drinks.png"),
  "face-tab": require("./img/categories/face.png"),
  "bodyparts-tab": require("./img/categories/bodyparts.png"),
  "colors-tab": require("./img/categories/colors.png"),
  "crafts-tab": require("./img/categories/crafts.png"),
  "shapes-tab": require("./img/categories/shapes.png"),
  "clothes-tab": require("./img/categories/clothes.png"),
  "weather-tab": require("./img/categories/weather.png"),
  "animals-tab": require("./img/categories/animals.png"),
  "transportation-tab": require("./img/categories/transportation.png")
};

export default images;
